<hr class="white">
<div class="span-35 prepend-1 append-1 last">
	<h2 class="alt">View Invoice</h2>
	<hr>
</div>

<div class="span-35 prepend-1 append-1 last">
	<h3>INVOICE</h3>
	<strong>Number: <?echo $this->invoiceNumber;?></strong>
	<br>
	<strong>Date: </strong>
	<hr class="white">
	<hr>
</div>

<div class="span-35 prepend-1 append-1 last">
	<h3>BILLING INFORMATION</h3>
	<div class="span-15 append-3">
		<strong>Tax Number</strong>
		<br>
		<?=($this->data['taxNumber'])?$this->data['taxNumber']:'-';?>
		<br>
		<strong>Company Name</strong>
		<br>
		<?=($this->data['taxCompany'])?$this->data['taxCompany']:'-';?>
		<br>
		<strong>Address</strong>
		<br>
		<?=($this->data['taxAddress'])?$this->data['taxAddress']:'-';?>
	</div>
	<div class="span-15 last">
		<strong>City</strong>
		<br>
		<?=($this->data['taxCity'])?$this->data['taxCity']:'-';?>
		<br>
		<strong>Zip</strong>
		<br>
		<?=($this->data['taxZip'])?$this->data['taxZip']:'-';?>
		<br>
		<strong>Province</strong>
		<br>
		<?=($this->data['taxProvince'])?$this->data['taxProvince']:'-';?>
		<br>
		<strong>Country</strong>
		<br>
		<?=($this->data['taxCountry'])?$this->data['taxCountry']:'-';?>
	</div>
</div>

<div class="span-35 prepend-1 append-1 last">
	<hr class="white">
	<h3>ORDER DETAILS</h3>
	<hr>
	<div class="span-19">
		<h4>Product Name</h4>
	</div>
	<div class="span-6">
		<h4>Price</h4>
	</div>
	<div class="span-5">
		<h4>Quantity</h4>
	</div>
	<div class="span-5 last">
		<h4>Total</h4>
	</div>
</div>

<div class="span-35 prepend-1 append-1 last">
	<hr>
	<?
		$bpmCatalog = new Kutu_Core_Bpm_Catalog();
		
		//var_dump($this->cart);
		
		$jcartId = $this->cart['items'];
		//$jcartProductInfo = $this->cart['iteminfo'];

		$iCart = 0;
		$cartTotal = 0;
		$price = 0;
		for($iCart=0;$iCart<count($jcartId);$iCart++)
		{
			$price = $bpmCatalog->getPrice($jcartId[$iCart]['itemId']);
			$cartTotal += $price;
	?>
			<div class="span-18 append-1">
				<strong><?echo $jcartId[$iCart]['item_name'];?></strong>
				<br>
				<?echo Kutu_Core_Util::getCatalogAttributeValue($jcartId[$iCart]['itemId'],'fixedSubTitle');	?>
				<br>&nbsp;
			</div>
			<div class="span-6">
				USD <?echo number_format($price,2);?>
			</div>
			<div class="span-5">
				1
			</div>
			<div class="span-5 last">
				USD <?echo number_format($price,2);?>
			</div>
			<hr>
	<?	}?>
</div>

<div class="span-35 prepend-1 append-1 last">
	<div class="span-5 prepend-25">
		<h4>Sub Total</h4>
	</div>
	<div class="span-5 last">
		<h4>USD <?echo number_format($cartTotal,2);?></h4>
	</div>
	<hr>
</div>
<div class="span-35 prepend-1 append-1 last">
	<div class="span-5 prepend-25">
		<h4>Tax 10%</h4>
	</div>
	<div class="span-5 last">
		<h4>USD <?echo number_format($this->cart['taxAmount'],2);?></h4>
	</div>
	<hr>
</div>
<div class="span-35 prepend-1 append-1 last">
	<div class="span-5 prepend-25">
		<h4>Grand Total (USD)</h4>
	</div>
	<div class="span-5 last">
		<h4>USD <?echo number_format($this->cart['grandTotal'],2);?></h4>
	</div>
	<hr>
</div>
<div class="span-35 prepend-1 append-1 last">
	<div class="span-5 prepend-25">
		<h4>Grand Total (IDR)</h4>
	</div>
	<div class="span-5 last">
		<h4>IDR <?echo number_format($this->cart['grandTotal']*$this->data['currencyValue'],2);?></h4>
	</div>
	<hr>
</div>

<!--div class="span-35 prepend-1 append-1 last">
	<h3>PAYMENT METHOD: <?=$this->data['paymentMethod'];?></h3>
</div -->
<div class="span-35 prepend-1 append-1 last">
	<font size="+1" color="red">SELECT PAYMENT METHOD: </font>
	<form method="get" action="<?=KUTU_ROOT_URL;?>/site/store_payment/index/orderId/<?=$this->orderId;?>">
		<select name="method" id="method" style="width:200px;">
			<!-- <option value="paypal" icon="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/US_AU_btn.gif">Paypal-->
			<option value="paypal" <?php if($this->data['paymentMethod']=='paypal') echo 'selected'?> >Paypal
			<option value="postpaid" <?php if($this->data['paymentMethod']=='postpaid') echo 'selected'?>>Postpaid
			<option value="bank" <?php if($this->data['paymentMethod']=='bank') echo 'selected'?>>Bank Transfer
		</select>
		<input type="submit" value="Continue with Payment" />
	</form>
	<hr class="white">
</div>

<div class="append-top">&nbsp;</div>


