<hr class="space">
<div class="container">
	<div class="span-33 prepend-2 append-2 last">
		<p>In order to confirm your request to join LGSONLINE Newsletters Service, a confirmation message has been sent to the following address: <strong>psykomo@yahoo.com</strong></p>

		<p>Please check your mailbox for this message. You must click on the link in the email message to confirm your subscription.</p>
	</div>
</div>