<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/aboutlgs_s.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?= KUTU_ROOT_URL;?>/pages/g/lgs4a1d79ad94802" style="color:#fff">About LGS</a></strong>
			<br>Brief Information about LGS 
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsfirm.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d7ab79b912" style="color:#fff">LGS Firm & Services</a></strong>
			<br>Track Records and Recent Transactions 
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsexp.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a4dc4239a6a7" style="color:#fff">LGS Experience</a></strong>
			<br>Giving you more than 30 years of excellent experience in state-of-the-arts corporate practices and commercial litigation
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgspartners.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a4dc4e9a29c6" style="color:#fff">LGS Partners</a></strong>
			<br>Get to know the Partners
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgslawyers.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a4dc57987c84" style="color:#fff">LGS Lawyers</a></strong>
			<br>Meet our lawyers
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsawards.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d8484cd013" style="color:#fff">LGS Awards</a></strong>
			<br>LGS Long Standing Achievements
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsothersay.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d84f8ab672" style="color:#fff">What Others Say About LGS</a></strong>
			<br>Recognition as Indonesia's Leading Law Firm and Lawyers 
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsnews.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d79809737a" style="color:#fff">LGS News</a></strong>
			<br>What Happens Inside LGS 
		</p>
	</div>
</div>
<div class='container'>
	<div class="span-2">
		<p><IMG src="<?echo KUTU_ROOT_URL;?>/common/modules/site/images/ico_lgsclients.jpg" /></p>
	</div>
	<div class="span-9 last">
		<p class="leftMenu"><strong><a href="<?=KUTU_ROOT_URL;?>/pages/g/lgs4a1d8494a0b6a" style="color:#fff">LGS Clients</a></strong>
			<br>Major Representatives of LGS Clients 
		</p>
	</div>
</div>