<?if($this->type == 'postpaid'){?>
	<div class="span-35 prepend-1 append-1 prepend-top last">
		<h2 class="alt">Postpaid Credit Limit Details</h2>
		<hr>
		<h3></h3>
		<legend>Postpaid</legend>
			<form method="post" action="../../postpaid">
				<div class="span-5">Total Postpaid Limit</div> 
				<div class="span-5" align="right"><?=$this->limit;?></div>
				<hr>
				<div class="span-5">Outstanding Postpaid Account</div>
				<div class="span-5 last" align="right"><?=number_format($this->outstandingAmount,2);?></div>
				<hr>
				<div class="span-5">Today's Total Transaction</div>
				<div class="span-5" align="right"><?=number_format($this->grandTotal,2); ?></div>
				<hr>	
				<div class="span-5">Remaining Limit</div>
				<div class="span-5" align="right"><?=$this->netLimit; ?> </div>
				<hr class="space">
				<input type="hidden" name="orderId" value="<?=$this->orderId?>">
				
				<hr class="white">
				<div class="span-18" align="">
				<input type="button" value= "back" onclick="javascript:history.back();" />
				<input type="submit" value="Pay with Remaining Credit"  />
				</div>
			
			</form>
			</fieldset>
			<hr class="white">
	</div>

<?}else{?>

<?}?>