<div class="container">
	<div class="span-33 append-2 prepend-2 prepend-top">
		<h2 class="alt">My Account</h2>
		<hr>
	</div>
</div>
<div class="container">
	<div class="span-33 append-2 prepend-2 prepend-top">
		<div class="span-25 colborder">
			<h4>Dashboard</h4>
			<p>Find all information about your account here.</p>

		</div>
		<div class="span-7 last">
			<?echo $this->widget1->render();?>
		</div>
	</div>
</div>


